// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wings.DataAccess;

namespace Wings.Migrations {
    [DbContext (typeof (WingsContext))]
    [Migration ("20190408163724_%date:~0,4%%date:~5,2%%date:~8,2%0%time:~1,1%%time:~3,2%%time:~6,2%")]
    partial class date04date52date820time11time32time62 {
        protected override void BuildTargetModel (ModelBuilder modelBuilder) {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation ("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation ("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity ("Wings.Base.RBAC.Entity.User", b => {
                b.Property<int> ("Id")
                    .ValueGeneratedOnAdd ()
                    .HasColumnName ("id")
                    .HasColumnType ("int(11)");

                b.Property<DateTime?> ("CreateTime2")
                    .HasColumnName ("createTime2")
                    .HasColumnType ("datetime");

                b.Property<string> ("Name")
                    .HasColumnName ("name")
                    .HasColumnType ("varchar(45)");

                b.HasKey ("Id");

                b.ToTable ("user");
            });
#pragma warning restore 612, 618
        }
    }
}